### ISSUE TITLE
Fatal error: Uncaught Exception: Sportlink API not found

### ISSUE THREAD

**Issue by adorlandt** [RichardVanDerMeer/wordpress-sportlink.club.dataservices#1]
I've installed the plugin in a clean WP environment. But when I go to settings and open the sportlink-KNVB page, i get the follwoning error:

![2019-07-31_20h12_08](https://user-images.githubusercontent.com/47195754/62236638-c4086f00-b3cf-11e9-9243-68c5c9e8af7e.png)

Fatal error: Uncaught Exception: Sportlink API not found in /home/domain/domains/mydomain.com/public_html/wordpress/wp-content/plugins/wordpress-sportlink.club.dataservices-master/sportlink.club.dataservices.php:196 Stack trace: #0 /home/domain/domains/mydomain.com/public_html/wordpress/wp-content/plugins/wordpress-sportlink.club.dataservices-master/sportlink.club.dataservices.php(184): SportlinkClient->connect() #1 /home/domain/domains/mydomain.com/public_html/wordpress/wp-content/plugins/wordpress-sportlink.club.dataservices-master/sportlink.club.dataservices.php(92): SportlinkClient->__construct(false, false) #2 /home/domain/domains/mydomain.com/public_html/wordpress/wp-includes/class-wp-hook.php(286): sportlink_club_dataservices_options('') #3 /home/domain/domains/mydomain.com/public_html/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /home/domain/domains/mydomain.com/public_html/wordpress/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #5 in /home/domain/domains/mydomain.com/public_html/wordpress/wp-content/plugins/wordpress-sportlink.club.dataservices-master/sportlink.club.dataservices.php on line 196

**Comment by abdallakamesh** [comment]
did you solve that ?
